### ISSUE TITLE
Remove VSCode dependency

### ISSUE THREAD

**Issue by johnsoncodehk** [yaegassy/coc-volar-experimental#2]
Thanks to create this coc extension!

This extension seem dependency VSCode, maybe helpful if I remove appRoot option and publish `@volar/vscode-server`?

**Comment by yaegassy** [comment]
Oh, I was surprised to receive a message from @johnsoncodehk. Thanks for checking out my validation repository. 🙇

If it works correctly without the `appRoot` setting, it would be helpful if the `appRoot` setting option could be removed.

Also, if you could publish `@volar/vscode-server` to "npm", it would make it possible for other editors, including Vim, to install the server smoothly.

---

On a different note, I would like to talk about HTML tag completion in `<templates>`.

Currently, I think it may not work without the built-in `html-language-features` in "Visual Studio Code". (I'm sorry if I'm wrong)

Other editors, such as Vim and Emacs, do not have `html-language-features`. :(

[VLS](https://github.com/vuejs/vetur/tree/master/server) (Vue Language Server) works comfortably with "HTML tag completion" in `<template>`.

It would be helpful if you could add HTML tag completion to `@volar/vscode-server` itself. 🙇

**Comment by johnsoncodehk** [comment]
`appRoot` config is used to require TS library, I can remove it but we need a new option to pass available TS library path to `@volar/vscode-server`. In this project you can install typescript and pass extension's `node_modules/typescript/lib` path to server.

html-language-features is not not necessary, but HTML tag completion is not a part of LSP, so we need to implement it in language client. See:

- https://github.com/johnsoncodehk/volar/blob/master/packages/vscode-client/src/features/tagClosing.ts#L7-L15
- https://github.com/microsoft/vscode/blob/main/extensions/html-language-features/client/src/tagClosing.ts

**Comment by yaegassy** [comment]
Thanks for the explanation. I'll be referring to them!

**Comment by yaegassy** [comment]
@johnsoncodehk 

I minimum ported `tagNameCase.ts` and `attrNameCase.ts`, and now I can auto complete "HTML tags", "component names", and "directives" in `<template>`.

<img width="780" alt="coc-volar-demo" src="https://user-images.githubusercontent.com/188642/127477834-461c3565-143a-4ce7-bd78-e68b8b304480.gif">

(I may have been mistaken about something)

Anyway, thanks for the advice!  🙇

**Comment by johnsoncodehk** [comment]
Sorry I thought you talking about the tag auto-closing feature. 🤣

Currently the language server relies on too many client requests, I will reduce it, and check for share the code of `@volar/language-client` to a certain extent.

Planned to be updated over the weekend.

**Comment by fannheyward** [comment]
> do not have html-language-features

@yaegassy does coc-html work for this? cic-html is a _almost_ clone of  html-language-features.

**Comment by yaegassy** [comment]
@fannheyward Thank you for the information. 🙇

I confirmed that volar can provide HTML tag completion by itself, but if I run coc-html, the HTML tag completion will be duplicated.

I interpreted html-language-features as being used for the tag-close feature, so I lowered the priority of the tag-close feature and removed the coc-html dependency once and for all.

**Comment by johnsoncodehk** [comment]
volar enable `html-language-features` to resolve https://github.com/microsoft/vscode/issues/98621. vscode 1.58 already fix it so volar will remove `html-language-features` and `css-language-features` in next version.

But still require `typescript-language-features` because it still use `setLanguageConfiguration` api. See https://github.com/microsoft/vscode/blob/main/extensions/typescript-language-features/src/languageFeatures/languageConfiguration.ts#L103.

I think this extension is not require `coc-html`, `coc-css`... at all, because it seem a vscode specific problem.

**Comment by johnsoncodehk** [comment]
Please use https://www.npmjs.com/package/@volar/server.
